apiVersion: v1
kind: Service
metadata:
  name: samplesql-mysql
  labels:
    app: samplesql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30066
  type: NodePort 
  selector:
    app: samplesql
    tier: mysql
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: samplesql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: samplesql-mysql
  labels:
    app: samplesql
spec:
  selector:
    matchLabels:
      app: samplesql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: samplesql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
